### ISSUE TITLE
No Modules & Dependencie Shown

### ISSUE THREAD

**Issue by gabriele-fanchini** [webpackmonitor/webpackmonitor#60]
Hello

my "Modules & Dependencie" shows nothing (as you can see in the image). There are no errors in the Chrome console. My actual configuration is the following:

`            new WebpackMonitor({
                capture: true,
                launch: true
            })`

Am i missing something?

![monitor](https://user-images.githubusercontent.com/2529879/31829485-aeb9e1e0-b5bd-11e7-9dab-a66e3e430140.PNG)

**Comment by mbehzad** [comment]
you probably are using this with webpack < v3.0. you could manually set the `chunkModules` property to true. something like: 
```
new WebpackMonitor({
      jsonOpts: { source: false, chunkModules: true },
      capture: ...
      target
      launch
      port
    })
```
make sure the stats.json in your monitor folder is deleted, otherwise you have to wait till your bundles are changed and the webpack monitor takes a new snapshot.
disclaimer:
the `jsonOpts` option is not documented in the github page. i'm not so sure if the user is supposed to change that. therefore i added a PR [#66](https://github.com/webpackmonitor/webpackmonitor/pull/66) for this to be set by default.

**Comment by neutraali** [comment]
`jsonOpts: { source: false, chunkModules: true }`

^ This fixed it for me :+1:

EDIT: Then again, now my **Assets** and **Total Build Size** is empty...

**Comment by gabriele-fanchini** [comment]
I updated to Webpack 3 and seems to work, thank you! :)
As far as I'am concerned this bug can be closed, but i noticed that @neutraali still have some problems;

Let me know if I have to close the bug or I have to let it open at the moment :) Thank you again!

**Comment by neutraali** [comment]
@gabriele-fanchini You can close this - We the switched to using the online version of webpack visualizer. We're still using a version of Webpack 2 so maybe it's fixed in version 3+ as you said.
